name: fingerprint
description: "ArchelStore App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  firebase_database: ^10.5.0
  firebase_storage: ^11.6.0
  
  # Fitur Utama
  local_auth: ^2.1.8
  intl: ^0.19.0
  url_launcher: ^6.2.0
  mailer: ^6.0.0
  image_picker: ^1.0.7
  crypto: ^3.0.3
  # UI & UX
  google_fonts: ^6.1.0
 
  carousel_slider: ^4.2.1
  pinput: ^4.0.0
  modal_bottom_sheet: ^3.0.0
  
  # GANTI INI (Hapus cool_alert, pakai quickalert)
  quickalert: ^1.0.0
  
  skeleton_text: ^3.0.0
  badges: ^3.1.2
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

# KONFIGURASI IKON
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true